version: "3.8"

services:
  php:
    build:
      context: '../'
      dockerfile: './docker/ci/php/fpm-dockerfile'
    container_name: open_loyalty_backend_test
    command: bash -c "phing ci-setup-test"
    depends_on:
      db:
        condition: service_healthy
      elk:
        condition: service_healthy
      mail:
        condition: service_started
    environment:
      SYMFONY__DATABASE_HOST: db
      SYMFONY__DATABASE_PORT: 5432
      SYMFONY__DATABASE_NAME: openloyalty
      SYMFONY__DATABASE_USER: openloyalty
      SYMFONY__DATABASE_PASSWORD: openloyalty
      SYMFONY__ELASTICA_HOST: elk
      SYMFONY__ELASTICA_PORT: 9200
      SYMFONY__MAILER_HOST: mail
      SYMFONY__MAILER_PORT: 1025

  db:
    image: postgres:9.6-alpine
    container_name: open_loyalty_db_test
    environment:
      POSTGRES_DB: openloyalty
      POSTGRES_USER: openloyalty
      POSTGRES_PASSWORD: openloyalty
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U openloyalty" ]
      interval: 10s
      timeout: 5s
      retries: 5

  elk:
    image: elasticsearch:2.4
    container_name: open_loyalty_elk_test
    environment:
      - ES_HEAP_SIZE=512m
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  mail:
    image: mailhog/mailhog:latest
    container_name: open_loyalty_mail_test
