version: "3.8"

services:
  php:
    build:
      context: '../'
      dockerfile: './docker/ci/php/fpm-dockerfile'
    container_name: open_loyalty_backend_test
    command: bash -c "phing ci-setup-test"
    depends_on:
      db:
        condition: service_healthy
      elk:
        condition: service_healthy
      mail:
        condition: service_started
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: openloyalty
      DATABASE_USER: openloyalty
      DATABASE_PASSWORD: openloyalty
      ELASTICSEARCH_HOST: elk
      MAIL_HOST: mail

  db:
    image: postgres:15-alpine
    container_name: open_loyalty_db_test
    environment:
      POSTGRES_DB: openloyalty
      POSTGRES_USER: openloyalty
      POSTGRES_PASSWORD: openloyalty
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U openloyalty" ]
      interval: 10s
      timeout: 5s
      retries: 5

  elk:
    image: elasticsearch:7.17.10
    container_name: open_loyalty_elk_test
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  mail:
    image: mailhog/mailhog:latest
    container_name: open_loyalty_mail_test
